name: marvelapp
description: A flutter application to list the marvel characters
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  http: ^0.13.1
  http_interceptor: ^0.4.0
  json_annotation: ^4.0.1
  crypto: ^3.0.0
  carousel_slider: ^3.0.0
  loader_overlay: ^2.0.0
  flutter_spinkit: "^4.1.2"
  mockito: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
